export default function Page() {
    return (
        <>
            <section>
                <div className="bg-primary text-white py-[46.5px]">

                </div>
            </section>
            <section>
                <div className="py-[100px]">
                    <div className="container">
                        <div className="text-[14px] sm:text-[16px] leading-relaxed grid grid-cols-1 gap-y-5 mb-7 text-text">
                            <h2 className="text-[25px] sm:text-[30px] font-bold text-black leading-snug">Refund & Cancelation Policy:</h2>
                            <p>The team at Click First SMM offers Refunds and Cancellations to all of its existing and new customers. The refund policy is subject to conditions and fair usage policy as mentioned below.</p>
                            <p>The customer can receive a full refund if he/she does not see month-on-month ROI for 3 months via leads, sales, appointments, store visits, inquiries, likes, follows, or any sort of engagement that applies as a KPI for the business to be set at the initiation of the service.</p>
                            <p>The fair usage policy enables the client to get a full refund any time after the end of the third month of service. The fair usage policy also enables the company for a window of 3 months to provide ample performance. Any refunds before the third month will be considered null and void in accordance to our fair usage policy.</p>
                            <p>The customer can also receive a full refund if the promised number of keywords are not ranked in the tenure promised in the contract provided. Any refunds before the ranking tenure promised will be considered null and void in accordance to our fair usage policy.</p>
                            <h3 className="text-[20px] font-semibold text-black leading-tight">Non-Disclosure Policy</h3>
                            <p>The team at Click First SMM is in formal binding of a non-disclosure agreement with each client we sign up with. By signing up as a client you agree to keep all communications, company assets, attachments, calls, and all type of interactions private thus playing an equal part of the non-disclosure agreement.</p>
                            <h3 className="text-[20px] font-semibold text-black leading-tight">Terms & Conditions</h3>
                            <p>ATTENTION: PLEASE READ THIS STATEMENT CAREFULLY BEFORE USING ClickFirstSMM (THIS “WEB SITE”). YOUR USE OF THIS WEB SITE CONSTITUTES YOUR ACCEPTANCE OF THIS COPYRIGHT STATEMENT AND TERMS OF USE (COLLECTIVELY, “TERMS OF USE”). IF YOU DO NOT ACCEPT THESE TERMS OF USE, DO NOT USE THIS WEB SITE.</p>
                            <p>ClickFirstSMM reserves the right to modify these Terms of Use without notice and any modifications are effective when they are posted here. ClickFirstSMM may, at any time, in its discretion terminate your access to this Web site. Access to the Web site may be monitored by ClickFirstSMM If you are accessing this Web site as a representative of an organization, these Terms of Use bind both you inpidually and the organization and references to “you” and “your” shall be construed to apply to you inpidually and the organization.</p>
                            <p>While ClickFirstSMM maintains copyright protection in all materials, information and publications (collectively, “Web site information”) it places on this Web site, ClickFirstSMM consents to normal downloading, copying and distribution of the information for non-commercial purposes by you or within your organization only. In consideration of this consent, you agree that copies of the Web site information will retain all copyright and other proprietary notices and that you will not modify the Web site information in any way. Except where your use constitutes “fair use” under copyright law, you may not otherwise use, download, upload, copy, print, display, perform, reproduce, publish, or distribute any Web site information, in whole or in part, without the prior written consent of ClickFirstSMM.</p>
                            <p>As a condition of your use of this Web site, you will not use the Web site or the Web site information for any purpose that is unlawful or prohibited by these Terms of Use. You will not use this Web site in any manner that could damage, disable, overload or impair the operation of this Web site or use by third parties.</p>
                            <p>Certain restricted product information is available on this Web site only to licensed customers of ClickFirstSMM that are registered to receive information via passwords issued by ClickFirstSMM This restricted information is considered confidential and proprietary information of ClickFirstSMM If you are a registered customer or a representative of a registered customer, ClickFirstSMM authorizes you to download, copy, distribute and use the restricted information for yourself or, if applicable, only within the customer organization, and only for the intended purposes authorized by ClickFirstSMM Issuance of a registration password is conditioned on the customer’s use of the information in accordance with the terms of its license or service agreement with ClickFirstSMM You shall not transfer your password to unauthorized parties. You will immediately notify ClickFirstSMM of any unauthorized use of your password. You are responsible for use of your password. You will not attempt to gain unauthorized access to any Web site information or area within this Web site.</p>
                            <p>You may link to the ClickFirstSMM home page, but are not authorized to link to any other page on the ClickFirstSMM Web site without the prior express written consent of ClickFirstSMM provided that ClickFirstSMM reserves the right to withdraw this consent at any time in its discretion. You may not use any of ClickFirstSMM proprietary logos, marks, or other distinctive graphics, video, or audio material in your links. You may not link in any manner reasonably likely to 1) imply affiliation with or endorsement or sponsorship by ClickFirstSMM 2) cause confusion, mistake, or deception; 3) dilute ClickFirstSMM trademarks, service marks or trade names; or 4) otherwise violate applicable law.</p>
                            <p>ClickFirstSMM makes no representations or promises to develop, provide or market any software, service or product discussed on this Web site, and you shall not rely on the information provided or the prospect of availability of any software, service or product currently in development or currently anticipated to be made available in the future.</p>
                            <p>Web site information may refer to products, programs or services that are not available in your country. Consult your ClickFirstSMM representative for information about the products, programs and services that may be available to you.</p>
                            <p>Any software that is available for download from this Web site is the copyrighted property of ClickFirstSMM and/or its suppliers. Any use or reproduction of any such software and warranties as to such software, if any, are governed by the terms of the license agreement applicable to that software. Any use of any other product or service and warranties as to such product or service purchased by you using, or in connection with, this Web site, if any, is governed by the terms of the agreement applicable to that product or service.</p>
                            <p>ClickFirstSMM makes no representations or promises to develop, provide or market any software, service or product discussed on this Web site, and you shall not rely on the information provided or the prospect of availability of any software, service or product currently in development or currently anticipated to be made available in the future.</p>
                            <p>Web site information may refer to products, programs or services that are not available in your country. Consult your ClickFirstSMM representative for information about the products, programs and services that may be available to you.</p>
                            <p>Any software that is available for download from this Web site is the copyrighted property of ClickFirstSMM and/or its suppliers. Any use or reproduction of any such software and warranties as to such software, if any, are governed by the terms of the license agreement applicable to that software. Any use of any other product or service and warranties as to such product or service purchased by you using, or in connection with, this Web site, if any, is governed by the terms of the agreement applicable to that product or service.</p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
}